---
- name: Create Alertmanager data volume
  containers.podman.podman_volume:
    name: '{{ alertmanager_hostname }}-1-data-volume'
    state: present
    label:
      app: alertmanager

- name: Set nginx proxy config
  template:
    src: alertmanager-proxy.conf
    dest: '{{ alertmanager_base_dir }}/{{ alertmanager_hostname }}-config/alertmanager-proxy.conf'
    mode: '0644'
#  notify:
#    - Restart Proxy

- name: Run Alertmanager container
  containers.podman.podman_container:
    name: '{{ alertmanager_hostname }}-1'
    image: 'quay.io/prometheus/alertmanager:v{{ alertmanager_version }}'
    pod: '{{ alertmanager_hostname }}-1-pod'
    conmon_pidfile: '{{ alertmanager_base_dir }}/pids/{{ alertmanager_hostname }}-1.pid'
    volume:
      - '{{ alertmanager_hostname }}-1-data-volume:/alertmanager'
      - '{{ alertmanager_base_dir }}/{{ alertmanager_hostname }}-config/alertmanager.yml:/etc/alertmanager/alertmanager.yml:z'
    command: '{{ alertmanager_1_flags }}'

- name: Run Nginx Proxy container
  containers.podman.podman_container:
    name: '{{ alertmanager_hostname }}-proxy-1'
    image: docker.io/library/nginx:latest
    pod: '{{ alertmanager_hostname }}-1-pod'
    conmon_pidfile: '{{ alertmanager_base_dir }}/pids/{{ alertmanager_hostname }}-proxy-1.pid'
    volume:
      - '{{ alertmanager_base_dir }}/{{ alertmanager_hostname }}-config/alertmanager-proxy.conf:/etc/nginx/conf.d/default.conf:z'

- name: Generate systemd unit files
  include_tasks: systemd.yml
  loop:
    - '{{ alertmanager_hostname }}-1'
    - '{{ alertmanager_hostname }}-proxy-1'
