---
# Create pods first to get cluster peer IP
- name: Create Alertmanager Pod(s)
  containers.podman.podman_pod:
    name: '{{ alertmanager_hostname }}-{{ item }}-pod'
    state: started
    network: '{{ alertmanager_podman_network }}'
    hostname: '{{ alertmanager_hostname }}-{{ item }}.{{ alertmanager_domain }}'
  loop: '{{ range(0, alertmanager_ha_replicas)|list }}'

- name: Get Alertmanager Pod Infra Container(s)
  containers.podman.podman_pod_info:
    name: '{{ alertmanager_hostname }}-{{ item }}-pod'
  register: pod_info
  loop: '{{ range(0, alertmanager_ha_replicas)|list }}'

- name: Get alertmanager pod infra container ID(s)
  set_fact:
    alertmanager_infra_ids: '{{ alertmanager_infra_ids|default([]) + [ pod_info.results[ item ].pods[0].InfraContainerID ] }}'
  loop: '{{ range(0, alertmanager_ha_replicas)|list }}'

- name: Get Infra Container info
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ alertmanager_infra_ids }}'

- name: Get alertmanager pod IP(s)
  set_fact:
    alertmanager_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ alertmanager_podman_network }}.IPAddress'

- name: Create cluster peer flag
  set_fact:
    alertmanager_cluster_peers: '{{ alertmanager_cluster_peers|default([]) + [ "--cluster.peer=" + item + ":" + alertmanager_cluster_listen_port|string ] }}'
  loop: '{{ alertmanager_pod_ips }}'

- name: Create flags clustered alertmanager
  set_fact:
    alertmanager_flags: '{{ alertmanager_flags + [ item ] }}'
  loop:
    - '--cluster.listen-address=0.0.0.0:{{ alertmanager_cluster_listen_port }}'
    - '{{ alertmanager_cluster_peers | join(" ") }}'
  when: alertmanager_ha_replicas > 1

- name: Join flags for alertmanager
  set_fact:
    alertmanager_flags: '{{ alertmanager_flags | join(" ") }}'

- debug:
    msg: '{{ alertmanager_flags }}'

- include_tasks: alertmanager.yml

- debug:
    msg:
    - '{{ alertmanager_hostname }}-{{ item }} pod IP: {{ alertmanager_pod_ips[ item ] }}'
  loop: '{{ range(0, alertmanager_ha_replicas)|list }}'
